### ISSUE TITLE
Channel  Randomizing

### ISSUE THREAD

**Issue by Splodgie** [spacehuhn/esp8266_beaconSpam#1]
Removed

**Comment by spacehuhn** [comment]
Thanks for the report!
I found the issue. The chip sends the packets on a random channel, but the beacon frame itself contains the wrong channel, but I couldn't find out why this yet.

**Comment by Splodgie** [comment]
Hi, thanks for looking into it, I've made a new small word list 128KB that takes in random known router names plus some out of the ssid.txt . But the give away is the fixed channel number on the rouge ones.
Q: could it be possible to store the ssid list direct on the ESP memory and call it from there. as I have chip modded all my ESP-01 to 4MB ?.
Dave

**Comment by spacehuhn** [comment]
Yes, you could store it inthe programm memory: https://www.arduino.cc/en/Reference/PROGMEM
I used that for the deauther project (look into data.h). 
The ESP8266 has also its own file system called SPIFFS, I never used it but it might be better/easier for certain things.

**Comment by spacehuhn** [comment]
Looking at this again over a year later, I can't think of any reason why someone would remove their question on something like this. Now this is a useless waste of memory in the internet void that will not help anyone anymore.

Thanks again @Splodgie .

**Comment by digmorepaka** [comment]
needs more bacon spam

**Comment by spacehuhn** [comment]
🥓

**Comment by digmorepaka** [comment]
🥓
