### ISSUE TITLE
issue with iPhones and Samsungs

### ISSUE THREAD

**Issue by savaof** [spacehuhn/esp8266_beaconSpam#17]
hi,  ssid's generated by this code are perfectly viewed on laptops, but iPhones and Samsungs can't see them. don't you know why can it happen?

**Comment by spacehuhn** [comment]
Can you tell me more about what devices you have tested it on and what OS?
I tested it on IOS4, IOS10 and Android 5 and 8 without problems.

**Comment by spacehuhn** [comment]
Try again now I made some improvements on the script.

**Comment by rjbhide** [comment]
Same issue on my Lenovo Android 7.0 mobile. I tried changing channel & setting wpa2=true. But no lock.

**Comment by spacehuhn** [comment]
Thanks, it's merged :)

**Comment by savaof** [comment]
@spacehuhn thanks a lot! everything works just fine
