### ISSUE TITLE
Some emoticons are not working

### ISSUE THREAD

**Issue by zoutepopcorn** [spacehuhn/esp8266_beaconSpam#19]
Hi I just started sending some emoticons.

It is a little buggy. But got it working:
https://github.com/zoutepopcorn/esp8266_beaconSpam/

Got it working on S7 and on other Androids. Wondering if iphone works and why it is buggy.

**Comment by spacehuhn** [comment]
Emoticons are unicode characters and not ascii, using those in a ssid can lead to problems. But that's fully depending on the client that is interpreting those SSIDs. 

But what do you mean with `buggy` ?

**Comment by zoutepopcorn** [comment]
> But what do you mean with buggy ?

Some of the characters are not working. 

When it fails the whole  list of SSIDs is not visible.

**Comment by spacehuhn** [comment]
Cool, also be that there is a 32 char limit and each emoji can take up to 4 characters!

**Comment by zoutepopcorn** [comment]
Yes, thanks for the reminder +1:
