### ISSUE TITLE
The WiFi networks always go away after a short period of time

### ISSUE THREAD

**Issue by andrewsalmon** [spacehuhn/esp8266_beaconSpam#3]
Instead of doing what I expected them to do, which was stay. They all disappear shortly.  

I'm a bit confused as to why this happens, and, if possible, how would I be able to keep these WiFi networks up (Pretty great and funny names haha) without them shutting down after ~5-10 seconds?(I counted and its around 15)  I'm just testing this on a NodeMCU

However this isn't the only issue. I wouldn't mind, but, then there are No WiFi networks for quite a while
~ 30-60 seconds.` Sometimes less, and sometimes more. As I was typing this, it first took 14 seconds for them to come back then 28. But when I first started it, it took around 30. Then I unplugged and replugged and it was almost immediate when starting. One thing is for sure though: Very inconsistent, 

I tried to look through the code and figure out if I could find what was causing this and I was a bit clueless;

P.s. I don't have an SD card (Since I'm on a NodeMCU, there isn't even a slot for one) and I'm using the default ones that load when you don't have an SD card

**Comment by Lunaous** [comment]
There is SPI on NodeMCU - Google it

**Comment by spacehuhn** [comment]
I might be a year late to answer this but try again, I updated the sketch. If you still have problems/questions, feel free to comment or make a new issue.
