### ISSUE TITLE
Same SSID not working

### ISSUE THREAD

**Issue by D33F4ULT** [spacehuhn/esp8266_beaconSpam#42]
When I enter the same SSID on multiple lines it shows only one WIFI SSID

**Comment by jLynx** [comment]
That is correct. The SSID's have to be different. Try adding incrementing spaces after each one

**Comment by D33F4ULT** [comment]
Can I somehow edit the code to show multiple networks with the same SSID without editing each line with spaces?

**Comment by jLynx** [comment]
Nope, it's fundamentally not possible

**Comment by D33F4ULT** [comment]
Ok, Thanks
